# Generated by Django 3.1.7 on 2021-04-02 13:20

from django.db import migrations
from django.db import models

import applications.blog.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at", "title", "author_id", "id"]},
        ),
        migrations.AddField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=applications.blog.models._utcnow
            ),
        ),
    ]
